# Generated by Django 5.1.2 on 2024-12-02 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0011_remove_menu_category_menu_category_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='category_id',
            new_name='category',
        ),
    ]
