# Generated by Django 5.1.2 on 2024-12-02 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0012_rename_category_id_menu_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='category',
            new_name='category_fk',
        ),
    ]
